// ********RoostGPT********
// Test generated by RoostGPT for test NodeTesting using AI Type Open AI and AI Model gpt-4-1106-preview



// ********RoostGPT********
const express = require('express');
const db = require('../models');

describe('App startup', () => {
  let server;

  beforeAll(async () => {
    jest.resetModules(); // Ensure that all modules are fresh before each test
    await db.sequelize.sync();
  });

  afterEach(() => {
    if (server && server.close) {
      server.close();
    }
  });

  test('should start the express app on port 8080 successfully', async () => {
    const app = express();
    server = app.listen(8080, () => {
      console.log("Server is listening on port 8080");
    });
    await new Promise(resolve => server.on('listening', resolve));
    const address = server.address();
    expect(address.port).toEqual(8080);
    expect(server).toBeDefined();
  });

  test('should throw an error if syncing the database fails', async () => {
    const originalSync = db.sequelize.sync;
    const error = new Error('Database sync failed');
    db.sequelize.sync = jest.fn().mockRejectedValue(error);

    await expect(db.sequelize.sync()).rejects.toThrow('Database sync failed');
    
    db.sequelize.sync = originalSync;
  });
});

